<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="button" Id="{980a9b75-0e1f-4e75-a249-8ef7030a659a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION button : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="button">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>