<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{163b8446-4c09-4e0f-b4e3-176ceac5542f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	READ  : INT;
	WRITE : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[READ := read +1 ;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>